// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package tutorial

import (
	"time"
)

type Account struct {
	ID          int64
	AccountName string
	Balance     int64
	Currency    string
	CreatedAt   time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccoutID    int64
	Amount        int64
	CreatedAt     time.Time
}

type User struct {
	ID        int64
	Username  string
	AccountID int64
	Amount    int64
	CreatedAt time.Time
}
