// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package tutorial

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO account (
    owner,
    balance,
    currency
) VALUES (
  $1, $2, $3
)
`

func (q *Queries) CreateAccount(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount)
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAccount)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, account_name, balance, currency, created_at FROM account
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAuthor)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, account_name, balance, currency, created_at FROM account
ORDER BY id
LIMIT 1
OFFSET 2
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE account
SET balance = $200
WHERE id = $1
`

func (q *Queries) UpdateAccount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateAccount)
	return err
}
